[Refactor] Removed blanketjs. Updated our git hook to run tests before commits

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,11 +1,23 @@
 #!/bin/sh
 #
-# Run JSHint validation before commit.
 
-files=$(git diff --cached --name-only --diff-filter=ACMR -- *.js **/*.js)
-
+# Go to repo root
 cd "$(git rev-parse --show-toplevel)"
 
+# Run functional tests
+node_modules/.bin/mocha --ui bdd --colors test/main.js -R min 2> testOutput
+isThereFailingTest=$(cat testOutput | grep failing | wc -l)
+rm testOutput
+
+if [ "$isThereFailingTest" -ne 0 ]; then
+    echo ""
+    echo "COMMIT FAILED:"
+    echo "There's a failing test."
+    echo "(Run run_tests.bat to see the errors)"
+    exit 1
+fi
+
+# Run style tests
 jshintLines=$(node_modules/.bin/jshint src/ | wc -l)
 jscsLines=$(node_modules/.bin/jscs src --config=.jscsrc | wc -l)
 result=$((jshintLines + jscsLines))
